In [1]:
import numpy as np

In [4]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
print(arr[3]) # untuk menampilkan value dari index ke-3
print(arr[1:5]) # untuk menampilkan value dari index ke-1 - ke - n-1
print(arr[0:5]) # untuk menampilkan value dari index ke-0 - ke - n-1

3
[1 2 3 4]
[0 1 2 3 4]


In [9]:
arr[0:5] = 100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [10]:
arr =  np.arange(11)
slice_of_arr = arr[0:6]
print(slice_of_arr)

[0 1 2 3 4 5]


In [14]:
slice_of_arr[ : ] = 99 # replace nilai pada keseluruhan index (:) menjadi 99 
print(slice_of_arr)
print(arr)

[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10]


In [15]:
arr_copy = arr.copy()
print(arr_copy)

[99 99 99 99 99 99  6  7  8  9 10]


### Indexing Array 2D

In [17]:
arr_2d = np.array(([5,10,15],
                  [20,25,30],
                  [35,40,45]))
print(arr_2d)
print(arr_2d.shape)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
(3, 3)


In [18]:
print(arr_2d[1]) # menampilkan elemen pada baris 1
print(arr_2d[1][0]) # menampilkan element pada baris 1 dan kolom 0
print(arr_2d[1,0]) # menampilkan element pada baris 1 dan kolom 0

[20 25 30]
20
20


In [19]:
print(arr_2d[:2,1:]) # menampilkan baris paling awal hingga baris ke 1, dan kolom ke-1 hingga kolom terakhri

[[10 15]
 [25 30]]


In [26]:
print(arr_2d[0::2,0::2])

[[ 5 15]
 [35 45]]


In [23]:
print(arr_2d[[0,2],:]) 

[[ 5 10 15]
 [35 40 45]]


In [24]:
arr_2d[[0,2],1] # jika ingin menagmbil > 1 baris atau 1 kolom maka gunakan []

array([10, 40])

In [32]:
a= np.zeros(3) # menampilkan vektor yang nilainya 0 sebanyak 3 elemen
print(a)

arr2d = np.zeros((10,10)) # menampilkan matriks or array 2D dengan 10 baris dan 10 kolom
print(arr2d)

[0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [42]:
arr_length = arr2d.shape[0] # menampilakan banyak rows dari suatu matriks 
arr_length1 = arr2d.shape[1] # menampilakan banyak columns dari suatu matriks 
print(arr_length)
print(arr_length1)

10
10


In [43]:
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [45]:
arr2d[[2,4,6,8]] # menampilkan baris ke-2,4,6, dan 8

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [47]:
arr2d[[6,4,2,7]] # menampilkan baris ke-6,4,2 dan 7

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

### Conditional Selection

In [51]:
arr = np.arange(1,11)
print(arr)
print(arr > 4) # hasilnya akan berupa boolean 
bool_arr = arr > 4
print(bool_arr)

print(arr[bool_arr])

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False  True  True  True  True  True  True]
[False False False False  True  True  True  True  True  True]
[ 5  6  7  8  9 10]


In [54]:
print(arr[arr > 4]) # menampilkan nilai yang sebenarnya yang > 4

[ 5  6  7  8  9 10]


In [55]:
x = 2
print(arr[arr > x])

[ 3  4  5  6  7  8  9 10]


## Numpy Operation

### Arithmatic array 1D

In [64]:
arr = np.arange(10)
print(arr)
print(arr + arr)
print(arr - arr)
print(arr*3)
print(arr/arr)
print(1/arr)
print(arr**3)
untung = arr - arr
print(untung)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[ 0  3  6  9 12 15 18 21 24 27]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]
[  0   1   8  27  64 125 216 343 512 729]
[0 0 0 0 0 0 0 0 0 0]


C:\Users\user only\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  
C:\Users\user only\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in true_divide
  import sys


#### Artihmatic 2D

In [75]:
matrix = np.arange(16).reshape(4,4)
print(matrix)
print(matrix+matrix)
print(matrix*matrix)
print(1/matrix)
print(matrix**3)
print(np.dot(matrix,matrix)) # np.dot adalah perkalian amtrix yang seharusnya

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]
[[       inf 1.         0.5        0.33333333]
 [0.25       0.2        0.16666667 0.14285714]
 [0.125      0.11111111 0.1        0.09090909]
 [0.08333333 0.07692308 0.07142857 0.06666667]]
[[   0    1    8   27]
 [  64  125  216  343]
 [ 512  729 1000 1331]
 [1728 2197 2744 3375]]
[[ 56  62  68  74]
 [152 174 196 218]
 [248 286 324 362]
 [344 398 452 506]]


C:\Users\user only\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


In [74]:
matrix1 = np.array(([1,2,3],
                   [4,5,6],
                   [7,8,9]))
print(matrix1)
print(matrix + matrix1) # gak bisa, karena beda shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


ValueError: operands could not be broadcast together with shapes (4,4) (3,3) 

In [77]:
a = np.array(([1,2],
              [4,5],
              [7,8]))
b = np.array(([9,10]))
print(a)
print(b)
print(np.dot(a,b))

[[1 2]
 [4 5]
 [7 8]]
[ 9 10]
[ 29  86 143]


In [87]:
print(arr)
print(np.sqrt(arr)) # hasil akar 
print(np.exp(arr)) # hasil eksponensia (e^)
print(np.max(arr)) # menampilkan nilai maks, dari sautu array
print(np.argmax(arr)) # mnampilkan index dari nilai maksimum 
print(np.sin(arr)) # menmapilkan nilai sinus
print(np.log(arr)) # menampilkan hasil log 

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
9
9
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


C:\Users\user only\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in log
  import sys


In [92]:
print(matrix)
print(np.exp(matrix))
print(np.max(matrix))
print(np.argmax(matrix))
print(np.log(matrix))s

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]
 [1.62754791e+05 4.42413392e+05 1.20260428e+06 3.26901737e+06]]
15
15
[[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]
 [2.07944154 2.19722458 2.30258509 2.39789527]
 [2.48490665 2.56494936 2.63905733 2.7080502 ]]


C:\Users\user only\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log
  """


In [94]:
print(arr)
print(np.where(arr > 5, 1, 0)) # np.where(cendition, True, False)

[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 0 1 1 1 1]


In [96]:
print(matrix)
print(np.where(matrix <= 10, 0, matrix))
print(np.where(matrix <= 10, 0, 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0 11]
 [12 13 14 15]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [1 1 1 1]]


## Series 

In [97]:
import pandas as pd

In [102]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
print(arr)
d = {'a':10, 'b' : 20, 'c' : 30}

[10 20 30]


In [99]:
pd.Series(data = my_list)

0    10
1    20
2    30
dtype: int64

In [103]:
pd.Series(data = my_list, index = labels)

a    10
b    20
c    30
dtype: int64

In [104]:
pd.Series(my_list, labels)

a    10
b    20
c    30
dtype: int64

In [105]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [106]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int32

In [109]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [110]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [112]:
ser1 = pd.Series([1,2,3,4], index= ['USA','Jerman','USSR','Japan'])
ser1

USA       1
Jerman    2
USSR      3
Japan     4
dtype: int64

In [115]:
ser2 = pd.Series([1,2,5,4], ['USA','Jerman','Italy','Japan'])
ser2

USA       1
Jerman    2
Italy     5
Japan     4
dtype: int64

In [116]:
ser1['USA']

1

In [118]:
ser1[['USA','Japan']] # apabila akan menampilkan > 1 index or label gunakan double []

USA      1
Japan    4
dtype: int64

In [119]:
ser1 + ser2 # penjumlahan pada series itu harus sama labelnya atau indexnya 

Italy     NaN
Japan     8.0
Jerman    4.0
USA       2.0
USSR      NaN
dtype: float64